name: PSScriptAnalyzer

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: '0 23 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "Run Module Analyzer"
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ..\..\Modules -Recurse -IncludeDefaultRules -ReportSummary -EnableExit



